spring.application.name=periodicals-system-spring
server.port=8081
server.servlet.context-path=/periodicals-spring

spring.datasource.url=jdbc:postgresql://localhost:5432/periodicals_spring_db
spring.datasource.username=postgres
spring.datasource.password=Vova

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Local testing mode. Set true when Keycloak or Auth0 is configured.
app.security.enabled=false

# For Keycloak/Auth0 real JWT mode, set app.security.enabled=true and issuer-uri.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/periodicals
